name: Frontend Docker Build & Push

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }} ${{ secrets.DOCKER_USERNAME }}/${{ inputs.service }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.service }}:latest
